name: Build and Tests

# Run this workflow every time a new PR wants to merge to master/main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Build
        run: go build ./...
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.51.2
          args: --skip-dirs=vendor
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Test
        run: make test
