name: Build and Tests

# Run this workflow every time a new PR wants to merge to master/main
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Build
        run: go build ./...
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vet
        run: go vet ./...
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Test
        run:
          make test
